export const wordsList = [
  {
    category: "país",
    items: [
      "afeganistao",
      "africa do sul",
      "albania",
      "alemanha",
      "angola",
      "arabia saudita",
      "argelia",
      "argentina",
      "armenia",
      "australia",
      "austria",
      "bahamas",
      "bangladexe",
      "barbados",
      "belgica",
      "belize",
      "bielorussia",
      "bolivia",
      "bosnia e herzegovina",
      "botsuana",
      "brasil",
      "bulgaria",
      "butao",
      "cabo verde",
      "camaroes",
      "camboja",
      "canada",
      "catar",
      "cazaquistao",
      "chile",
      "china",
      "chipre",
      "colombia",
      "coreia do norte",
      "coreia do sul",
      "cosovo",
      "costa do marfim",
      "costa rica",
      "croacia",
      "cuaite",
      "cuba",
      "dinamarca",
      "egito",
      "emirados arabes unidos",
      "equador",
      "eslovaquia",
      "eslovenia",
      "espanha",
      "estados unidos",
      "estonia",
      "etiopia",
      "fiji",
      "filipinas",
      "finlandia",
      "frança",
      "gana",
      "georgia",
      "grecia",
      "guatemala",
      "guiana",
      "guine",
      "haiti",
      "honduras",
      "hungria",
      "iemen",
      "india",
      "indonesia",
      "irao",
      "iraque",
      "irlanda",
      "islandia",
      "israel",
      "italia",
      "jamaica",
      "japao",
      "jordania",
      "letonia",
      "liberia",
      "libia",
      "lituania",
      "luxemburgo",
      "macedonia do norte",
      "madagascar",
      "malasia",
      "malaui",
      "maldivas",
      "malta",
      "mauricia",
      "mexico",
      "mianmar",
      "moçambique",
      "moldavia",
      "montenegro",
      "monaco",
      "mongolia",
      "namibia",
      "nepal",
      "nicaragua",
      "nigeria",
      "noruega",
      "nova zelandia",
      "paises baixos",
      "panama",
      "papua nova guine",
      "paquistao",
      "paraguai",
      "peru",
      "polonia",
      "portugal",
      "quenia",
      "reino unido",
      "republica checa",
      "republica dominicana",
      "romenia",
      "russia",
      "senegal",
      "serra leoa",
      "servia",
      "singapura",
      "siria",
      "somalia",
      "sri lanca",
      "sudao",
      "sudao do sul",
      "suecia",
      "suiça",
      "suriname",
      "tailandia",
      "taiwan",
      "tanzania",
      "tunisia",
      "turquia",
      "ucrania",
      "uganda",
      "uruguai",
      "vaticano",
      "venezuela",
      "vietname",
      "zambia",
      "zimbabue",
    ],
  },
  {
    category: "legume",
    items: [
      "abobora",
      "abobrinha",
      "aipim",
      "alho",
      "amaranto",
      "amendoa",
      "amendoim",
      "andu",
      "arroz",
      "aveia",
      "avela",
      "azeitona",
      "baroa",
      "batata",
      "batata doce",
      "berdana",
      "berinjela",
      "beterraba",
      "cara",
      "castanha de baru",
      "castanha de caju",
      "castanha de macaco",
      "castanha do maranhao",
      "castanha do para",
      "castanheiro do mato",
      "caxi",
      "cebola",
      "cenoura",
      "centeio",
      "cevada",
      "chalota",
      "chia",
      "chicha",
      "chuchu",
      "dende",
      "ervilha",
      "fava",
      "feijao",
      "fruta pao",
      "gengibre",
      "gergelim",
      "goya",
      "grao de bico",
      "inhame",
      "jaca verde",
      "jalapeno",
      "jilo",
      "labaca",
      "lentilha",
      "linhaça",
      "lirio do brejo",
      "macassa",
      "malagueta",
      "malte",
      "mandioca",
      "mandioquinha",
      "maxixe",
      "mendubiguaçu",
      "milho",
      "mitsuba",
      "mogango",
      "moranga",
      "nabo",
      "noz",
      "oliva",
      "palmito",
      "pepino",
      "pequi",
      "pimenta",
      "pimentao",
      "pinhao",
      "pistache",
      "quiabo",
      "quinoa",
      "rabanete",
      "soja",
      "tomate",
      "tomate cereja",
      "tonka",
      "trigo",
      "urucum",
      "vagem",
      "wasabi",
      "xixa",
    ],
  },
  {
    category: "verdura",
    items: [
      "açafrao",
      "acelga",
      "agriao",
      "aipo",
      "alcachofra",
      "alcaparra",
      "alecrim",
      "alface",
      "alho poro",
      "almeirao",
      "aspargo",
      "brocolis",
      "caruru",
      "cebolinha",
      "chicoria",
      "coentro",
      "couve",
      "couve flor",
      "cidreira",
      "erva doce",
      "mate",
      "espinafre",
      "hibisco",
      "hortela",
      "louro",
      "manjericao",
      "manjerona",
      "mostarda",
      "oregano",
      "palma",
      "picao",
      "repolho",
      "rucula",
      "salsa",
      "salsao",
      "salvia",
      "tomilho",
      "urtiga",
      "vinagreira",
    ],
  },
  {
    category: "cor",
    items: [
      "verde",
      "amarelo",
      "azul",
      "branco",
      "vermelho",
      "preto",
      "cinza",
      "marrom",
      "roxo",
      "laranja",
      "rosa",
    ],
  },
  {
    category: "pedra preciosa",
    items: [
      "agata",
      "alexandrite",
      "ambar",
      "ametista",
      "azurita",
      "diamante",
      "esmeralda",
      "granada",
      "hematita",
      "jade",
      "jasper",
      "cianita",
      "lapis lazuli",
      "malaquita",
      "pedra da lua",
      "obsidiana",
      "opala",
      "perola",
      "peridoto",
      "quartzo",
      "rubi",
      "safira",
      "topazio",
      "turmalina",
      "turquesa",
    ],
  },
  {
    category: "metal pesado",
    items: [
      "sodio",
      "potassio",
      "calcio",
      "bario",
      "ferro",
      "zinco",
      "cobre",
      "niquel",
      "magnesio",
      "arsenio",
      "chumbo",
      "cadmio",
      "mercurio",
      "aluminio",
      "titanio",
      "estanho",
      "tungstenio",
      "cromo",
      "cobalto",
      "maganes",
    ],
  },
];
