export const wordsList = [
  {
    category: "país",
    items: [
      "brasil",
      "estados unidos",
      "africa do sul",
      "panama",
      "portugal",
      "espanha",
      "suica",
      "mexico",
      "china",
      "japao",
    ],
  },
  {
    category: "legume",
    items: [
      "abobora",
      "feijao",
      "cenoura",
      "mandioca",
      "batata",
      "cebola",
      "beterraba",
      "rabanete",
      "nabo",
      "arroz",
    ],
  },
  {
    category: "veículo",
    items: [
      "carro",
      "moto",
      "barco",
      "aviao",
      "bicicleta",
      "helicoptero",
      "onibus",
      "caminhao",
      "carroca",
    ],
  },
  {
    category: "cor",
    items: [
      "azul",
      "vermelho",
      "preto",
      "laranja",
      "branco",
      "amarelo",
      "cinza",
      "rosa",
      "roxo",
      "marrom",
    ],
  },
];
